name: Integration test

on: [push, pull_request]

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Install LXD
      if: ${{ !env.ACT }}
      shell: bash
      # language=bash
      run: |
        set -euxo pipefail
        sudo lxd waitready
        sudo lxd init --auto
        sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
        echo "/snap/bin" >> $GITHUB_PATH
    - name: Install juju
      shell: bash
      env: 
        JUJU_CHANNEL: "3.0/stable"
      # language=bash
      run: |
        set -euxo pipefail
        sudo snap install juju --channel=$JUJU_CHANNEL
        # lxc network set lxdbr0 ipv6.address none
    - name: Bootstrap controller
      shell: bash
      # language=bash
      run: |
        sudo mkdir /home/runner/.ssh
        juju bootstrap localhost test --debug    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: pip install tox
    - name: Run unit tests
      run: tox -e py3
    - name: Run integration
      run: tox -e py3 -e integration,serial
